# Generated by Django 3.2.9 on 2022-11-05 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project_time_tracking.api.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_required', models.TextField(validators=[project_time_tracking.api.utils.validators.validate_time_data])),
                ('time_spent', models.TextField(validators=[project_time_tracking.api.utils.validators.validate_time_data])),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('done', 'Done'), ('inprogress', 'Inprogress'), ('complted', 'Complted')], default='todo', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, null=True)),
                ('task', models.ManyToManyField(to='api.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='logs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='api.tasklog'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ManyToManyField(to='api.Project'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled')], default='pending', max_length=200, null=True)),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.ManyToManyField(to='api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.projectmember'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='api.task'),
        ),
    ]
